### ISSUE TITLE
batch_cholesky not found

### ISSUE THREAD

**Issue by elena-zamfir** [ICL-SML/gptf#2]
I've just installed gptf and tried going through the notebooks. 
I get an error message when trying to use compute_prior_samples: AttributeError: 'module' object has no attribute 'batch_cholesky'
I have installed tensorflow version 0.11.0rc0 and it seems the batch_\* functions  have been eliminated:
Eliminated batch_\* methods for most linear algebra and FFT ops and promoted the non-batch version of the ops to handle batches of matrices. 
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/p1yk23KvH0c

**Comment by mpd37** [comment]
Thanks for the info. We moved forward to TF 0.11. Please check out the
new version and see whether it works now.

**Comment by elena-zamfir** [comment]
Thank you!
I had replaced 'batch_cholesky' with 'cholesky' myself in the models.py
 file and it worked.
Elena
