### ISSUE TITLE
How to install gptf by pip

### ISSUE THREAD

**Issue by wmmxk** [ICL-SML/gptf#3]
Thanks for developing API. I tried to install gptf using pip install gptf and got an popup saying Could not find a version that satisfies the requirement gptf . Could you explain how to install it? Thanks for your time.

**Comment by mpd37** [comment]
Can you try again? This may be related to an issue in the setup.py file. I hope this is fixed now.

**Comment by PaperclipBadger** [comment]
As far as I know, gptf is not available on PyPI – that’s why pip is giving you an error. There are installation instruction available in the README.md in the github repository at https://github.com/ICL-SML/gptf, but I’ll explain in more detail:

First, install TensorFlow 0.11 or higher using the installation instructions here: https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation
Then clone the github repo for gptf:

$ git clone https://github.com/ICL-SML/gptf.git
$ cd gptf

To install for python 2, or if using a virtualenv:

$ python setup.py develop

 

To install for python 3:

$ python3 setup.py develop
