### ISSUE TITLE
ARD=True fails

### ISSUE THREAD

**Issue by sliem** [ICL-SML/gptf#5]
I'm trying to use the ARD option.

Quick example adopted from the Gaussian_process_regression.ipynb notebook.

    import gptf
    import numpy as np

    gp = gptf.gpr.GPR(
        gptf.kernels.RBF(ARD=True),
        noise_variance=.25
    )

    X = np.random.uniform(0., 5., (50, 2))
    Y = gp.compute_prior_samples(X, 1, 1)[0]`

With `ARD=False` this script works fine but with `ARD=True` we get the following traceback:

    $ python example.py
    Traceback (most recent call last):
      File "example.py", line 10, in <module>
        Y = gp.compute_prior_samples(X, 1, 1)[0]
      File "/Users/seal/Documents/gptf/gptf/core/wrappedtf.py", line 692, in wrapper
        result = method(instance, *args, **kwargs)
      File "/Users/seal/Documents/gptf/gptf/core/params.py", line 1439, in wrapper
        { 'op': method(instance, *tf_args)
      File "/Users/seal/Documents/gptf/gptf/core/models.py", line 511, in compute_prior_samples
        mu, var = self.build_prior_mean_var(test_points, num_latent, True)
      File "/Users/seal/Documents/gptf/gptf/core/trees.py", line 1050, in wrapper
        method_cache[key] =  method(instance, *args, **kwargs)
      File "/Users/seal/Documents/gptf/gptf/core/wrappedtf.py", line 692, in wrapper
        result = method(instance, *args, **kwargs)
      File "/Users/seal/Documents/gptf/gptf/gpr.py", line 110, in build_prior_mean_var
        fvar = self.kernel.K(X)
      File "/Users/seal/Documents/gptf/gptf/core/trees.py", line 1050, in wrapper
        method_cache[key] =  method(instance, *args, **kwargs)
      File "/Users/seal/Documents/gptf/gptf/core/wrappedtf.py", line 692, in wrapper
        result = method(instance, *args, **kwargs)
      File "/Users/seal/Documents/gptf/gptf/core/kernels.py", line 396, in K
        base = np.ones((dim,))
      File "/Users/seal/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 192, in ones
        a = empty(shape, dtype, order)
    TypeError: 'NoneType' object cannot be interpreted as an integer

I added a `print(X)` at gptf/core/kernels.py:393 and got the following output 

    Tensor("gp.compute_prior_samples/Placeholder:0", shape=(?, ?), dtype=float64)

I'm no expert in TensorFlow but it seems to be that the data hasn't been feed to the placeholder and thus it cannot determine the dimensionality yet.

A possible solution would be to changed the API and require the user to specify the dimensionality when constructing the kernel. I could whip up a pull request with this if this is how you want to handle it.

**Comment by PaperclipBadger** [comment]
Which version of TensorFlow are you using?

**Comment by sliem** [comment]
0.12.1

**Comment by sliem** [comment]
I tried 0.11, didn't help.

I tried changing the code to use tf.shape(X) and tf.ones(tf.shape(X)) in [Stationary.K() in kernels.py](https://github.com/ICL-SML/gptf/blob/master/gptf/core/kernels.py#L387). The idea was that the length scales would be calculated when the graph is being executed. This was thwarted by the length scales being wrapped by Param which expects numpy values.

I look into the [GPflow implementation of Stationary](https://github.com/GPflow/GPflow/blob/master/GPflow/kernels.py#L290) which require the specification of input_dim. I can simply port that.

**Comment by PaperclipBadger** [comment]
Ah, I see what's happening here. I think it might be possible to be cleverer with how we construct the placeholders in the `gptf.params.autoflow` decorator. Currently, we provide the specifications for the placeholders at decoration time, and then use them as a kind of rudimentary type-checking for the arguments. Because we can't know the exact dimensions of the arguments at decoration time, we specify them as `[None, None]`.

However, we don't actually construct the placeholders (nor indeed compile the wrapped tensorflow op) until the decorated function is called. At that point, we do know the precise dimensions of the input, so we can construct more accurate placeholders.

**Comment by sliem** [comment]
Hmm, good idea. I modified the `gptf.params.autoflow` at line [1437](https://github.com/ICL-SML/gptf/blob/master/gptf/core/params.py#L1437) to accept a 'infer' option instead of a tuple. I.e.

    #tf_args = [tf.placeholder(*s) for s in placeholder_specs]
    tf_args = []
    for i, s in enumerate(placeholder_specs):
        if s[1] == 'infer':
            s = (s[0], (None, np_args[i].shape[1]))
        tf_args.append(tf.placeholder(*s))

Modifying the autoflow decorator call at compute_prior_samples then becomes:

    #@autoflow((tf.float64, [None, None]), (tf.int32, []), (tf.int32, []))
    @autoflow((tf.float64, 'infer'), (tf.int32, []), (tf.int32, []))
    def compute_prior_samples(self, test_points, num_latent, num_samples):

This seems to work given some minimal testing. The syntax should be modified so that one can specify which dimensions one want to infer on. I.e. something like `(tf.float64, [None, 'infer'])`.

When is specifying the dimensionality is not a good idea? For instance in the above option the dimensionality must be `[None, some_integer]` so I could call compute_prior_sample with Xes of different length.

**Comment by PaperclipBadger** [comment]
I've pushed an update to autoflow that fixes this issue, improves caching, adds support for wrapping specific arguments by name and reduces the number of duplicate methods in the library. The new interface looks like this:

```python
import gptf
import tensorflow as tf

class Example(gptf.Parameterized):
    @autoflow('a', 'b')  # wrapped args are specified by their names
    def tf_add(self, a, b):
        return tf.add(a, b)

    @autoflow('a b')  # we can also provide a space-separated list
    def tf_op(a, b, kind='add'):
        if kind == 'add':
            return tf.add(a, b)
        elif kind == 'subtract':
            return tf.subtract(a, b)

    # we can provide type-checking using keyword arguments.
    @autoflow(a=(tf.float64, (None, 'infer')), b=('infer', (None, Ellipsis)))
    def tf_batch_add(a, b):
          return tf.add(a, b)
```

The decorator also adds a `autoflow_specs` keyword argument to the function, which allows you to override the default inferred specifications at call time:

```python
m = Example()
m.tf_add([[5.]], [[7.], [5.], [6.]], autoflow_specs={'b': (tf.float64, [None, 1])}
```

See the [documentation for autoflow](https://icl-sml.github.io/gptf/build/html/public_api.html#autoflow) for more details.
