### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zegee** [ICL-SML/gptf#6]
Please, I am trying to run the Product of Expert Model.However on I encountered this problem:AttributeError: 'BoundArguments' object has no attribute 'apply_defaults' when I tried to run this line:Y = full_gp.compute_prior_samples(X, 1, 1)[0].Is there any to resolve this?

**Comment by PaperclipBadger** [comment]
Can you give me a code sample?

**Comment by PaperclipBadger** [comment]
Ah, I've think I've found the problem, Are you using Python 3.4 by any chance?

**Comment by Zegee** [comment]
yes please

**Comment by Zegee** [comment]
Sorry for the delay in response, I was preparing for an exam as well.

**Comment by Zegee** [comment]
So please, how do I resolve the problem?

**Comment by PaperclipBadger** [comment]
I've pushed what should be a fix. Try
```bash
pip install --upgrade gptf
```

**Comment by Zegee** [comment]
from IPython.display import display_html
import gptf
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

full_gp = gptf.gpr.GPR(
    gptf.kernels.RBF(variance=10.),
    noise_variance=.25
)
X = np.random.uniform(0., 5., (20, 1))
Y = full_gp.compute_prior_samples(X, 1, 1)[0]
Y += np.random.normal(0., np.sqrt(full_gp.likelihood.variance.value),
                      Y.shape) 
full_gp.optimize(X, Y, disp=False)
display_html(full_gp.summary(fmt='html'), raw=True)

**Comment by Zegee** [comment]
Above is how the code looks like, I thought may be after upgrading gptf,the problem will be solve but it has generated another error below:I am putting all this here for details:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-423186e329d0> in <module>()
     10 )
     11 X = np.random.uniform(0., 5., (20, 1))
---> 12 Y = full_gp.compute_prior_samples(X, 1, 1)[0]
     13 Y += np.random.normal(0., np.sqrt(full_gp.likelihood.variance.value),
     14                       Y.shape)  # add noise

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/wrappedtf.py in wrapper(instance, *args, **kwargs)
    690                     stack.enter_context(tf.name_scope(scope))
    691 
--> 692                 result = method(instance, *args, **kwargs)
    693 
    694                 if name_scope and rename_output:

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/params.py in wrapper(instance, *args, **kwargs)
   1563 
   1564             # add tf_method wrapper for memoisation etc
-> 1565             op = wrapped_method(*binding.args, **binding.kwargs)
   1566 
   1567             with instance.get_session() as sess:

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/trees.py in wrapper(instance, *args, **kwargs)
   1068             else:
   1069                 if key not in method_cache:
-> 1070                     method_cache[key] =  method(instance, *args, **kwargs)
   1071                 return method_cache[key]
   1072         return wrapper

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/wrappedtf.py in wrapper(instance, *args, **kwargs)
    690                     stack.enter_context(tf.name_scope(scope))
    691 
--> 692                 result = method(instance, *args, **kwargs)
    693 
    694                 if name_scope and rename_output:

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/models.py in compute_prior_samples(self, test_points, num_latent, num_samples)
    508         num_samples = tf.cast(num_samples, tf.int32)
    509 
--> 510         mu, var = self.build_prior_mean_var(test_points, num_latent, True)
    511         jitter = tfhacks.eye(tf.shape(mu)[0], var.dtype) * 1e-06
    512         L = tf.cholesky(tf.transpose(var, (2, 0, 1)) + jitter)

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/trees.py in wrapper(instance, *args, **kwargs)
   1068             else:
   1069                 if key not in method_cache:
-> 1070                     method_cache[key] =  method(instance, *args, **kwargs)
   1071                 return method_cache[key]
   1072         return wrapper

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/wrappedtf.py in wrapper(instance, *args, **kwargs)
    690                     stack.enter_context(tf.name_scope(scope))
    691 
--> 692                 result = method(instance, *args, **kwargs)
    693 
    694                 if name_scope and rename_output:

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/gpr.py in build_prior_mean_var(self, test_points, num_latent, full_cov)
    109         fmean += tf.zeros([1, num_latent], fmean.dtype)  # broadcast mu
    110         if full_cov:
--> 111             fvar = self.kernel.K(X)
    112             fvar = tf.tile(tf.expand_dims(fvar, 2), (1, 1, num_latent))
    113         else:

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/trees.py in wrapper(instance, *args, **kwargs)
   1059 
   1060             binding = sig.bind(*args, **kwargs)
-> 1061             binding.apply_defaults()
   1062             key = tuple(sorted(binding.arguments.items()))
   1063 

/home/charles/MyPython_Envs/project1/lib/python3.4/site-packages/gptf/core/__init__.py in apply_defaults(self)
      3         for param in self.signature.parameters.values():
      4             if (param.name not in self.arguments and 
----> 5                     param.default is not Parameter.empty):
      6                 self.arguments[param.name] = param.default
      7     BoundArguments.apply_defaults = apply_defaults

NameError: name 'Parameter' is not defined

​

​

​

​

**Comment by PaperclipBadger** [comment]
Pushed a fix for the fix. Try upgrading again?

**Comment by Zegee** [comment]
Hi Rogers, it works!
I am very glad!
Thank you!
I am a student of Professor Marc Deisenroth,I learnt from your linkin page that you work with him sometime ago.My full name is Avornyo Charles. I will like to contact you through your email.Hope that is ok?

**Comment by PaperclipBadger** [comment]
Yes, that's fine. You should be able to get my e-mail from Marc.
